# Generated by Django 4.2.7 on 2023-11-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='job_offers',
        ),
    ]
