# Generated by Django 4.2.7 on 2023-11-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Becario', 'Becario'), ('Temporal', 'Temporal'), ('Contrato', 'Contrato')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
