# Generated by Django 4.2.7 on 2023-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_rename_expiration_date_joboffer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
