# Generated by Django 4.2.7 on 2023-11-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_remove_employerprofile_job_offers'),
        ('job_offers', '0003_alter_joboffer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='employer',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employer_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='employers.employerprofile'),
        ),
    ]
