# Generated by Django 4.2.7 on 2023-11-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='certificaciones',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='educacion',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='idiomas',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resumen',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
