# Generated by Django 4.2.7 on 2023-11-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_remove_candidateprofile_certificaciones_and_more'),
        ('job_offers', '0005_joboffer_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Submitted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.joboffer')),
            ],
        ),
    ]
